// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.1
// source: common/token_processed_event.proto

package common_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenProcessed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UriData      string            `protobuf:"bytes,500,opt,name=uri_data,json=uriData,proto3" json:"uri_data,omitempty"`
	Description  string            `protobuf:"bytes,501,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl     string            `protobuf:"bytes,502,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	SocialMedias map[string]string `protobuf:"bytes,503,rep,name=social_medias,json=socialMedias,proto3" json:"social_medias,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ThumbUrl     string            `protobuf:"bytes,504,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"`
}

func (x *TokenProcessed) Reset() {
	*x = TokenProcessed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_token_processed_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenProcessed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenProcessed) ProtoMessage() {}

func (x *TokenProcessed) ProtoReflect() protoreflect.Message {
	mi := &file_common_token_processed_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenProcessed.ProtoReflect.Descriptor instead.
func (*TokenProcessed) Descriptor() ([]byte, []int) {
	return file_common_token_processed_event_proto_rawDescGZIP(), []int{0}
}

func (x *TokenProcessed) GetUriData() string {
	if x != nil {
		return x.UriData
	}
	return ""
}

func (x *TokenProcessed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TokenProcessed) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TokenProcessed) GetSocialMedias() map[string]string {
	if x != nil {
		return x.SocialMedias
	}
	return nil
}

func (x *TokenProcessed) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

var File_common_token_processed_event_proto protoreflect.FileDescriptor

var file_common_token_processed_event_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xad, 0x02,
	0x0a, 0x0e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x72, 0x69, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0xf4, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x69, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0xf5, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0xf6, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x5f, 0x0a,
	0x0d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x18, 0xf7,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x2e, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x0c, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0xf8, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x72, 0x6c, 0x1a, 0x3f, 0x0a, 0x11,
	0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_token_processed_event_proto_rawDescOnce sync.Once
	file_common_token_processed_event_proto_rawDescData = file_common_token_processed_event_proto_rawDesc
)

func file_common_token_processed_event_proto_rawDescGZIP() []byte {
	file_common_token_processed_event_proto_rawDescOnce.Do(func() {
		file_common_token_processed_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_token_processed_event_proto_rawDescData)
	})
	return file_common_token_processed_event_proto_rawDescData
}

var file_common_token_processed_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_token_processed_event_proto_goTypes = []interface{}{
	(*TokenProcessed)(nil), // 0: io.chainstream.v1.token.TokenProcessed
	nil,                    // 1: io.chainstream.v1.token.TokenProcessed.SocialMediasEntry
}
var file_common_token_processed_event_proto_depIdxs = []int32{
	1, // 0: io.chainstream.v1.token.TokenProcessed.social_medias:type_name -> io.chainstream.v1.token.TokenProcessed.SocialMediasEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_token_processed_event_proto_init() }
func file_common_token_processed_event_proto_init() {
	if File_common_token_processed_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_token_processed_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenProcessed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_token_processed_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_token_processed_event_proto_goTypes,
		DependencyIndexes: file_common_token_processed_event_proto_depIdxs,
		MessageInfos:      file_common_token_processed_event_proto_msgTypes,
	}.Build()
	File_common_token_processed_event_proto = out.File
	file_common_token_processed_event_proto_rawDesc = nil
	file_common_token_processed_event_proto_goTypes = nil
	file_common_token_processed_event_proto_depIdxs = nil
}
