// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.1
// source: common/token_price_event.proto

package common_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenPriceEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*TokenPriceEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *TokenPriceEvents) Reset() {
	*x = TokenPriceEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_token_price_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenPriceEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPriceEvents) ProtoMessage() {}

func (x *TokenPriceEvents) ProtoReflect() protoreflect.Message {
	mi := &file_common_token_price_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPriceEvents.ProtoReflect.Descriptor instead.
func (*TokenPriceEvents) Descriptor() ([]byte, []int) {
	return file_common_token_price_event_proto_rawDescGZIP(), []int{0}
}

func (x *TokenPriceEvents) GetEvents() []*TokenPriceEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TokenPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress  string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	PriceInUsd    string `protobuf:"bytes,2,opt,name=price_in_usd,json=priceInUsd,proto3" json:"price_in_usd,omitempty"`
	PriceInNative string `protobuf:"bytes,3,opt,name=price_in_native,json=priceInNative,proto3" json:"price_in_native,omitempty"`
}

func (x *TokenPrice) Reset() {
	*x = TokenPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_token_price_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPrice) ProtoMessage() {}

func (x *TokenPrice) ProtoReflect() protoreflect.Message {
	mi := &file_common_token_price_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPrice.ProtoReflect.Descriptor instead.
func (*TokenPrice) Descriptor() ([]byte, []int) {
	return file_common_token_price_event_proto_rawDescGZIP(), []int{1}
}

func (x *TokenPrice) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenPrice) GetPriceInUsd() string {
	if x != nil {
		return x.PriceInUsd
	}
	return ""
}

func (x *TokenPrice) GetPriceInNative() string {
	if x != nil {
		return x.PriceInNative
	}
	return ""
}

type TokenPriceEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instruction *Instruction `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Block       *Block       `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Transaction *Transaction `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	DApp        *DApp        `protobuf:"bytes,4,opt,name=d_app,json=dApp,proto3" json:"d_app,omitempty"`
	TokenPrice  *TokenPrice  `protobuf:"bytes,200,opt,name=token_price,json=tokenPrice,proto3" json:"token_price,omitempty"`
}

func (x *TokenPriceEvent) Reset() {
	*x = TokenPriceEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_token_price_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenPriceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPriceEvent) ProtoMessage() {}

func (x *TokenPriceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_token_price_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPriceEvent.ProtoReflect.Descriptor instead.
func (*TokenPriceEvent) Descriptor() ([]byte, []int) {
	return file_common_token_price_event_proto_rawDescGZIP(), []int{2}
}

func (x *TokenPriceEvent) GetInstruction() *Instruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

func (x *TokenPriceEvent) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *TokenPriceEvent) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TokenPriceEvent) GetDApp() *DApp {
	if x != nil {
		return x.DApp
	}
	return nil
}

func (x *TokenPriceEvent) GetTokenPrice() *TokenPrice {
	if x != nil {
		return x.TokenPrice
	}
	return nil
}

var File_common_token_price_event_proto protoreflect.FileDescriptor

var file_common_token_price_event_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1d, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x1a,
	0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x10, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x46, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x7b, 0x0a, 0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x5f,
	0x75, 0x73, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x55, 0x73, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x6e, 0x5f, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x4e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x22, 0xdc, 0x02,
	0x0a, 0x0f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x47, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x69,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x05, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6f, 0x2e, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x47, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x05, 0x64, 0x5f,
	0x61, 0x70, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6f, 0x2e, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x41, 0x70, 0x70, 0x52, 0x04, 0x64, 0x41, 0x70, 0x70, 0x12,
	0x4b, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0xc8,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x52, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_token_price_event_proto_rawDescOnce sync.Once
	file_common_token_price_event_proto_rawDescData = file_common_token_price_event_proto_rawDesc
)

func file_common_token_price_event_proto_rawDescGZIP() []byte {
	file_common_token_price_event_proto_rawDescOnce.Do(func() {
		file_common_token_price_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_token_price_event_proto_rawDescData)
	})
	return file_common_token_price_event_proto_rawDescData
}

var file_common_token_price_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_token_price_event_proto_goTypes = []interface{}{
	(*TokenPriceEvents)(nil), // 0: io.chainstream.v1.token.price.TokenPriceEvents
	(*TokenPrice)(nil),       // 1: io.chainstream.v1.token.price.TokenPrice
	(*TokenPriceEvent)(nil),  // 2: io.chainstream.v1.token.price.TokenPriceEvent
	(*Instruction)(nil),      // 3: io.chainstream.v1.common.Instruction
	(*Block)(nil),            // 4: io.chainstream.v1.common.Block
	(*Transaction)(nil),      // 5: io.chainstream.v1.common.Transaction
	(*DApp)(nil),             // 6: io.chainstream.v1.common.DApp
}
var file_common_token_price_event_proto_depIdxs = []int32{
	2, // 0: io.chainstream.v1.token.price.TokenPriceEvents.events:type_name -> io.chainstream.v1.token.price.TokenPriceEvent
	3, // 1: io.chainstream.v1.token.price.TokenPriceEvent.instruction:type_name -> io.chainstream.v1.common.Instruction
	4, // 2: io.chainstream.v1.token.price.TokenPriceEvent.block:type_name -> io.chainstream.v1.common.Block
	5, // 3: io.chainstream.v1.token.price.TokenPriceEvent.transaction:type_name -> io.chainstream.v1.common.Transaction
	6, // 4: io.chainstream.v1.token.price.TokenPriceEvent.d_app:type_name -> io.chainstream.v1.common.DApp
	1, // 5: io.chainstream.v1.token.price.TokenPriceEvent.token_price:type_name -> io.chainstream.v1.token.price.TokenPrice
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_common_token_price_event_proto_init() }
func file_common_token_price_event_proto_init() {
	if File_common_token_price_event_proto != nil {
		return
	}
	file_common_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_common_token_price_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenPriceEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_token_price_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_token_price_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenPriceEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_token_price_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_token_price_event_proto_goTypes,
		DependencyIndexes: file_common_token_price_event_proto_depIdxs,
		MessageInfos:      file_common_token_price_event_proto_msgTypes,
	}.Build()
	File_common_token_price_event_proto = out.File
	file_common_token_price_event_proto_rawDesc = nil
	file_common_token_price_event_proto_goTypes = nil
	file_common_token_price_event_proto_depIdxs = nil
}
