// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.1
// source: common/token_supply_processed_event.proto

package common_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketCap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress      string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	TotalSupplyAmount string `protobuf:"bytes,2,opt,name=total_supply_amount,json=totalSupplyAmount,proto3" json:"total_supply_amount,omitempty"`
	MarketCapInNative string `protobuf:"bytes,3,opt,name=market_cap_in_native,json=marketCapInNative,proto3" json:"market_cap_in_native,omitempty"`
	MarketCapInUsd    string `protobuf:"bytes,4,opt,name=market_cap_in_usd,json=marketCapInUsd,proto3" json:"market_cap_in_usd,omitempty"`
}

func (x *MarketCap) Reset() {
	*x = MarketCap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_token_supply_processed_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketCap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketCap) ProtoMessage() {}

func (x *MarketCap) ProtoReflect() protoreflect.Message {
	mi := &file_common_token_supply_processed_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketCap.ProtoReflect.Descriptor instead.
func (*MarketCap) Descriptor() ([]byte, []int) {
	return file_common_token_supply_processed_event_proto_rawDescGZIP(), []int{0}
}

func (x *MarketCap) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *MarketCap) GetTotalSupplyAmount() string {
	if x != nil {
		return x.TotalSupplyAmount
	}
	return ""
}

func (x *MarketCap) GetMarketCapInNative() string {
	if x != nil {
		return x.MarketCapInNative
	}
	return ""
}

func (x *MarketCap) GetMarketCapInUsd() string {
	if x != nil {
		return x.MarketCapInUsd
	}
	return ""
}

var File_common_token_supply_processed_event_proto protoreflect.FileDescriptor

var file_common_token_supply_processed_event_proto_rawDesc = []byte{
	0x0a, 0x29, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x73,
	0x75, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x69, 0x6f, 0x2e,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x22, 0xbc, 0x01, 0x0a, 0x09,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43, 0x61, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2e,
	0x0a, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f,
	0x0a, 0x14, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x61, 0x70, 0x5f, 0x69, 0x6e, 0x5f,
	0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x43, 0x61, 0x70, 0x49, 0x6e, 0x4e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x12,
	0x29, 0x0a, 0x11, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x61, 0x70, 0x5f, 0x69, 0x6e,
	0x5f, 0x75, 0x73, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x43, 0x61, 0x70, 0x49, 0x6e, 0x55, 0x73, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_common_token_supply_processed_event_proto_rawDescOnce sync.Once
	file_common_token_supply_processed_event_proto_rawDescData = file_common_token_supply_processed_event_proto_rawDesc
)

func file_common_token_supply_processed_event_proto_rawDescGZIP() []byte {
	file_common_token_supply_processed_event_proto_rawDescOnce.Do(func() {
		file_common_token_supply_processed_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_token_supply_processed_event_proto_rawDescData)
	})
	return file_common_token_supply_processed_event_proto_rawDescData
}

var file_common_token_supply_processed_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_token_supply_processed_event_proto_goTypes = []interface{}{
	(*MarketCap)(nil), // 0: io.chainstream.v1.token.supply.MarketCap
}
var file_common_token_supply_processed_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_token_supply_processed_event_proto_init() }
func file_common_token_supply_processed_event_proto_init() {
	if File_common_token_supply_processed_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_token_supply_processed_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketCap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_token_supply_processed_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_token_supply_processed_event_proto_goTypes,
		DependencyIndexes: file_common_token_supply_processed_event_proto_depIdxs,
		MessageInfos:      file_common_token_supply_processed_event_proto_msgTypes,
	}.Build()
	File_common_token_supply_processed_event_proto = out.File
	file_common_token_supply_processed_event_proto_rawDesc = nil
	file_common_token_supply_processed_event_proto_goTypes = nil
	file_common_token_supply_processed_event_proto_depIdxs = nil
}
