# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/balance_event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/balance_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2
from common import balance_processed_event_pb2 as common_dot_balance__processed__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommon/balance_event.proto\x12\x19io.chainstream.v1.balance\x1a\x13\x63ommon/common.proto\x1a$common/balance_processed_event.proto\"H\n\rBalanceEvents\x12\x37\n\x06\x65vents\x18\x01 \x03(\x0b\x32\'.io.chainstream.v1.balance.BalanceEvent\"\xeb\x01\n\x07\x42\x61lance\x12\x1d\n\x15token_account_address\x18\x01 \x01(\t\x12\x1d\n\x15\x61\x63\x63ount_owner_address\x18\x02 \x01(\t\x12\x15\n\rtoken_address\x18\x03 \x01(\t\x12\x12\n\npre_amount\x18\x04 \x01(\t\x12\x13\n\x0bpost_amount\x18\x05 \x01(\t\x12\x15\n\x08\x64\x65\x63imals\x18\x06 \x01(\rH\x00\x88\x01\x01\x12>\n\tlifecycle\x18\x64 \x01(\x0e\x32+.io.chainstream.v1.balance.AccountLifecycleB\x0b\n\t_decimals\"\xe3\x02\n\x0c\x42\x61lanceEvent\x12:\n\x0binstruction\x18\x01 \x01(\x0b\x32%.io.chainstream.v1.common.Instruction\x12.\n\x05\x62lock\x18\x02 \x01(\x0b\x32\x1f.io.chainstream.v1.common.Block\x12:\n\x0btransaction\x18\x03 \x01(\x0b\x32%.io.chainstream.v1.common.Transaction\x12-\n\x05\x64_app\x18\x04 \x01(\x0b\x32\x1e.io.chainstream.v1.common.DApp\x12\x33\n\x07\x62\x61lance\x18\x64 \x01(\x0b\x32\".io.chainstream.v1.balance.Balance\x12G\n\x11\x62\x61lance_processed\x18\xc8\x01 \x01(\x0b\x32+.io.chainstream.v1.balance.BalanceProcessed*\x8e\x01\n\x10\x41\x63\x63ountLifecycle\x12!\n\x1d\x41\x43\x43OUNT_LIFECYCLE_UNSPECIFIED\x10\x00\x12\x19\n\x15\x41\x43\x43OUNT_LIFECYCLE_NEW\x10\x01\x12\x1e\n\x1a\x41\x43\x43OUNT_LIFECYCLE_EXISTING\x10\x02\x12\x1c\n\x18\x41\x43\x43OUNT_LIFECYCLE_CLOSED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.balance_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTLIFECYCLE']._serialized_start=787
  _globals['_ACCOUNTLIFECYCLE']._serialized_end=929
  _globals['_BALANCEEVENTS']._serialized_start=116
  _globals['_BALANCEEVENTS']._serialized_end=188
  _globals['_BALANCE']._serialized_start=191
  _globals['_BALANCE']._serialized_end=426
  _globals['_BALANCEEVENT']._serialized_start=429
  _globals['_BALANCEEVENT']._serialized_end=784
# @@protoc_insertion_point(module_scope)
