# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/balance_processed_event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/balance_processed_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$common/balance_processed_event.proto\x12\x19io.chainstream.v1.balance\"\x88\x01\n\x10\x42\x61lanceProcessed\x12\x1c\n\x14pre_amount_in_native\x18\x64 \x01(\t\x12\x19\n\x11pre_amount_in_usd\x18\x65 \x01(\t\x12\x1e\n\x15post_amount_in_native\x18\xc8\x01 \x01(\t\x12\x1b\n\x12post_amount_in_usd\x18\xc9\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.balance_processed_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BALANCEPROCESSED']._serialized_start=68
  _globals['_BALANCEPROCESSED']._serialized_end=204
# @@protoc_insertion_point(module_scope)
