# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/candlestick_agg.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/candlestick_agg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ommon/candlestick_agg.proto\x12\x1dio.chainstream.v1.candlestick\"\xc2\x04\n\x13\x43\x61ndlestickAggCache\x12\x15\n\rtoken_address\x18\x01 \x01(\t\x12\x13\n\x0bunique_keys\x18\x02 \x03(\t\x12\x12\n\nresolution\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x19\n\x11open_block_height\x18\x05 \x01(\x04\x12\x1e\n\x16open_transaction_index\x18\x06 \x01(\r\x12\x1e\n\x16open_instruction_index\x18\x07 \x01(\r\x12\x0c\n\x04open\x18\x08 \x01(\t\x12\x16\n\x0eopen_in_native\x18\t \x01(\t\x12\x0c\n\x04high\x18\n \x01(\t\x12\x16\n\x0ehigh_in_native\x18\x0b \x01(\t\x12\x0b\n\x03low\x18\x0c \x01(\t\x12\x15\n\rlow_in_native\x18\r \x01(\t\x12\r\n\x05\x63lose\x18\x0e \x01(\t\x12\x17\n\x0f\x63lose_in_native\x18\x0f \x01(\t\x12\x1a\n\x12\x63lose_block_height\x18\x10 \x01(\x04\x12\x1f\n\x17\x63lose_transaction_index\x18\x11 \x01(\r\x12\x1f\n\x17\x63lose_instruction_index\x18\x12 \x01(\r\x12\x15\n\raverage_price\x18\x13 \x01(\t\x12\x1f\n\x17\x61verage_price_in_native\x18\x14 \x01(\t\x12\x0e\n\x06volume\x18\x15 \x01(\t\x12\x15\n\rvolume_in_usd\x18\x16 \x01(\t\x12\x18\n\x10volume_in_native\x18\x17 \x01(\t\x12\x0e\n\x06trades\x18\x18 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.candlestick_agg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANDLESTICKAGGCACHE']._serialized_start=64
  _globals['_CANDLESTICKAGGCACHE']._serialized_end=642
# @@protoc_insertion_point(module_scope)
