# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/dex_pool_processed_event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/dex_pool_processed_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%common/dex_pool_processed_event.proto\x12\x1aio.chainstream.v1.dex.pool\"n\n\x0eTokenLiquidity\x12\x15\n\rtoken_address\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\x12\x1b\n\x13liquidity_in_native\x18\x03 \x01(\t\x12\x18\n\x10liquidity_in_usd\x18\x04 \x01(\t\"\xaf\x06\n\x10\x44\x65xPoolProcessed\x12 \n\x18token_a_amount_in_native\x18\x14 \x01(\t\x12\x1d\n\x15token_a_amount_in_usd\x18\x15 \x01(\t\x12*\n\"token_a_vault_pre_amount_in_native\x18\x16 \x01(\t\x12\'\n\x1ftoken_a_vault_pre_amount_in_usd\x18\x17 \x01(\t\x12+\n#token_a_vault_post_amount_in_native\x18\x18 \x01(\t\x12(\n token_a_vault_post_amount_in_usd\x18\x19 \x01(\t\x12\x45\n\x11token_a_liquidity\x18\x1e \x01(\x0b\x32*.io.chainstream.v1.dex.pool.TokenLiquidity\x12I\n\x15token_a_max_liquidity\x18( \x01(\x0b\x32*.io.chainstream.v1.dex.pool.TokenLiquidity\x12 \n\x18token_b_amount_in_native\x18x \x01(\t\x12\x1d\n\x15token_b_amount_in_usd\x18y \x01(\t\x12*\n\"token_b_vault_pre_amount_in_native\x18z \x01(\t\x12\'\n\x1ftoken_b_vault_pre_amount_in_usd\x18{ \x01(\t\x12+\n#token_b_vault_post_amount_in_native\x18| \x01(\t\x12(\n token_b_vault_post_amount_in_usd\x18} \x01(\t\x12\x46\n\x11token_b_liquidity\x18\x82\x01 \x01(\x0b\x32*.io.chainstream.v1.dex.pool.TokenLiquidity\x12J\n\x15token_b_max_liquidity\x18\x8c\x01 \x01(\x0b\x32*.io.chainstream.v1.dex.pool.TokenLiquidity\x12\x1b\n\x12owner_dapp_program\x18\x96\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.dex_pool_processed_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENLIQUIDITY']._serialized_start=69
  _globals['_TOKENLIQUIDITY']._serialized_end=179
  _globals['_DEXPOOLPROCESSED']._serialized_start=182
  _globals['_DEXPOOLPROCESSED']._serialized_end=997
# @@protoc_insertion_point(module_scope)
