# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/token_processed_event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/token_processed_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"common/token_processed_event.proto\x12\x17io.chainstream.v1.token\"\xe9\x01\n\x0eTokenProcessed\x12\x11\n\x08uri_data\x18\xf4\x03 \x01(\t\x12\x14\n\x0b\x64\x65scription\x18\xf5\x03 \x01(\t\x12\x12\n\timage_url\x18\xf6\x03 \x01(\t\x12Q\n\rsocial_medias\x18\xf7\x03 \x03(\x0b\x32\x39.io.chainstream.v1.token.TokenProcessed.SocialMediasEntry\x12\x12\n\tthumb_url\x18\xf8\x03 \x01(\t\x1a\x33\n\x11SocialMediasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.token_processed_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENPROCESSED_SOCIALMEDIASENTRY']._loaded_options = None
  _globals['_TOKENPROCESSED_SOCIALMEDIASENTRY']._serialized_options = b'8\001'
  _globals['_TOKENPROCESSED']._serialized_start=64
  _globals['_TOKENPROCESSED']._serialized_end=297
  _globals['_TOKENPROCESSED_SOCIALMEDIASENTRY']._serialized_start=246
  _globals['_TOKENPROCESSED_SOCIALMEDIASENTRY']._serialized_end=297
# @@protoc_insertion_point(module_scope)
