# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/token_price_event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/token_price_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ommon/token_price_event.proto\x12\x1dio.chainstream.v1.token.price\x1a\x13\x63ommon/common.proto\"R\n\x10TokenPriceEvents\x12>\n\x06\x65vents\x18\x01 \x03(\x0b\x32..io.chainstream.v1.token.price.TokenPriceEvent\"R\n\nTokenPrice\x12\x15\n\rtoken_address\x18\x01 \x01(\t\x12\x14\n\x0cprice_in_usd\x18\x02 \x01(\t\x12\x17\n\x0fprice_in_native\x18\x03 \x01(\t\"\xa9\x02\n\x0fTokenPriceEvent\x12:\n\x0binstruction\x18\x01 \x01(\x0b\x32%.io.chainstream.v1.common.Instruction\x12.\n\x05\x62lock\x18\x02 \x01(\x0b\x32\x1f.io.chainstream.v1.common.Block\x12:\n\x0btransaction\x18\x03 \x01(\x0b\x32%.io.chainstream.v1.common.Transaction\x12-\n\x05\x64_app\x18\x04 \x01(\x0b\x32\x1e.io.chainstream.v1.common.DApp\x12?\n\x0btoken_price\x18\xc8\x01 \x01(\x0b\x32).io.chainstream.v1.token.price.TokenPriceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.token_price_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENPRICEEVENTS']._serialized_start=86
  _globals['_TOKENPRICEEVENTS']._serialized_end=168
  _globals['_TOKENPRICE']._serialized_start=170
  _globals['_TOKENPRICE']._serialized_end=252
  _globals['_TOKENPRICEEVENT']._serialized_start=255
  _globals['_TOKENPRICEEVENT']._serialized_end=552
# @@protoc_insertion_point(module_scope)
