# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/token_market_cap_event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/token_market_cap_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2
from common import token_supply_processed_event_pb2 as common_dot_token__supply__processed__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#common/token_market_cap_event.proto\x12\"io.chainstream.v1.token.market_cap\x1a\x13\x63ommon/common.proto\x1a)common/token_supply_processed_event.proto\"_\n\x14TokenMarketCapEvents\x12G\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x37.io.chainstream.v1.token.market_cap.TokenMarketCapEvent\"\xab\x02\n\x13TokenMarketCapEvent\x12:\n\x0binstruction\x18\x01 \x01(\x0b\x32%.io.chainstream.v1.common.Instruction\x12.\n\x05\x62lock\x18\x02 \x01(\x0b\x32\x1f.io.chainstream.v1.common.Block\x12:\n\x0btransaction\x18\x03 \x01(\x0b\x32%.io.chainstream.v1.common.Transaction\x12-\n\x05\x64_app\x18\x04 \x01(\x0b\x32\x1e.io.chainstream.v1.common.DApp\x12=\n\nmarket_cap\x18\x64 \x01(\x0b\x32).io.chainstream.v1.token.supply.MarketCapb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.token_market_cap_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENMARKETCAPEVENTS']._serialized_start=139
  _globals['_TOKENMARKETCAPEVENTS']._serialized_end=234
  _globals['_TOKENMARKETCAPEVENT']._serialized_start=237
  _globals['_TOKENMARKETCAPEVENT']._serialized_end=536
# @@protoc_insertion_point(module_scope)
