# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/token_supply_event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/token_supply_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2
from common import token_supply_processed_event_pb2 as common_dot_token__supply__processed__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63ommon/token_supply_event.proto\x12\x1eio.chainstream.v1.token.supply\x1a\x13\x63ommon/common.proto\x1a)common/token_supply_processed_event.proto\"U\n\x11TokenSupplyEvents\x12@\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x30.io.chainstream.v1.token.supply.TokenSupplyEvent\"\xa8\x01\n\x0bTokenSupply\x12\x15\n\rtoken_address\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x12\x10\n\x08\x64\x65\x63imals\x18\x03 \x01(\r\x12\x1f\n\x17\x61mount_without_decimals\x18\x04 \x01(\t\x12\x1c\n\x14\x61mount_with_decimals\x18\x05 \x01(\t\x12!\n\x19post_amount_with_decimals\x18\x06 \x01(\t\"\xb0\x03\n\x10TokenSupplyEvent\x12:\n\x0binstruction\x18\x01 \x01(\x0b\x32%.io.chainstream.v1.common.Instruction\x12.\n\x05\x62lock\x18\x02 \x01(\x0b\x32\x1f.io.chainstream.v1.common.Block\x12:\n\x0btransaction\x18\x03 \x01(\x0b\x32%.io.chainstream.v1.common.Transaction\x12-\n\x05\x64_app\x18\x04 \x01(\x0b\x32\x1e.io.chainstream.v1.common.DApp\x12\x42\n\x04type\x18\x64 \x01(\x0e\x32\x34.io.chainstream.v1.token.supply.TokenSupplyEventType\x12\x41\n\x0ctoken_supply\x18\x65 \x01(\x0b\x32+.io.chainstream.v1.token.supply.TokenSupply\x12>\n\nmarket_cap\x18\xc9\x01 \x01(\x0b\x32).io.chainstream.v1.token.supply.MarketCap*\xe6\x01\n\x14TokenSupplyEventType\x12\'\n#TOKEN_SUPPLY_EVENT_TYPE_UNSPECIFIED\x10\x00\x12+\n\'TOKEN_SUPPLY_EVENT_TYPE_INITIALIZE_MINT\x10\x01\x12 \n\x1cTOKEN_SUPPLY_EVENT_TYPE_MINT\x10\x02\x12 \n\x1cTOKEN_SUPPLY_EVENT_TYPE_BURN\x10\x03\x12\x34\n0TOKEN_SUPPLY_EVENT_TYPE_INITIALIZE_MINT_FROM_RPC\x10\x63\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.token_supply_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENSUPPLYEVENTTYPE']._serialized_start=825
  _globals['_TOKENSUPPLYEVENTTYPE']._serialized_end=1055
  _globals['_TOKENSUPPLYEVENTS']._serialized_start=131
  _globals['_TOKENSUPPLYEVENTS']._serialized_end=216
  _globals['_TOKENSUPPLY']._serialized_start=219
  _globals['_TOKENSUPPLY']._serialized_end=387
  _globals['_TOKENSUPPLYEVENT']._serialized_start=390
  _globals['_TOKENSUPPLYEVENT']._serialized_end=822
# @@protoc_insertion_point(module_scope)
