# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/trade_processed_event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/trade_processed_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"common/trade_processed_event.proto\x12\x1bio.chainstream.v1.dex.trade\x1a\x13\x63ommon/common.proto\"\xfa\x03\n\x0eTradeProcessed\x12\x1e\n\x16token_a_price_in_quote\x18\x01 \x01(\t\x12\x1c\n\x14token_a_price_in_usd\x18\x02 \x01(\t\x12\x1f\n\x17token_a_price_in_native\x18\x03 \x01(\t\x12\x1d\n\x15token_b_price_in_base\x18\x04 \x01(\t\x12\x1c\n\x14token_b_price_in_usd\x18\x05 \x01(\t\x12\x1f\n\x17token_b_price_in_native\x18\x06 \x01(\t\x12\'\n\x1fis_token_a_price_in_usd_suspect\x18\x65 \x01(\x08\x12\x64\n&is_token_a_price_in_usd_suspect_reason\x18\x66 \x01(\x0e\x32\x34.io.chainstream.v1.dex.trade.TokenPriceSuspectReason\x12$\n\x1btoken_a_price_in_usd_lasted\x18\xc8\x01 \x01(\t\x12\'\n\x1etoken_a_price_in_native_lasted\x18\xc9\x01 \x01(\t\x12$\n\x1btoken_b_price_in_usd_lasted\x18\xd2\x01 \x01(\t\x12\'\n\x1etoken_b_price_in_native_lasted\x18\xd3\x01 \x01(\t*\x9c\x03\n\x17TokenPriceSuspectReason\x12*\n&TOKEN_PRICE_SUSPECT_REASON_UNSPECIFIED\x10\x00\x12\x33\n/TOKEN_PRICE_SUSPECT_REASON_BY_LAST_CLOSE_PRICES\x10\x01\x12\x35\n1TOKEN_PRICE_SUSPECT_REASON_BY_SMALL_AMOUNT_IN_USD\x10\x02\x12+\n\'TOKEN_PRICE_SUSPECT_REASON_BY_BIG_PRICE\x10\x03\x12:\n6TOKEN_PRICE_SUSPECT_REASON_BY_CONSTANT_PRODUCT_FORMULA\x10\x04\x12\x33\n/TOKEN_PRICE_SUSPECT_REASON_BY_POOL_PRICE_IMPACT\x10\x05\x12K\nGTOKEN_PRICE_SUSPECT_REASON_BY_SMALL_AMOUNT_IN_USD_AND_POOL_PRICE_IMPACT\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.trade_processed_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENPRICESUSPECTREASON']._serialized_start=598
  _globals['_TOKENPRICESUSPECTREASON']._serialized_end=1010
  _globals['_TRADEPROCESSED']._serialized_start=89
  _globals['_TRADEPROCESSED']._serialized_end=595
# @@protoc_insertion_point(module_scope)
