# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/transfer_processed_event.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'common/transfer_processed_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%common/transfer_processed_event.proto\x12\x1aio.chainstream.v1.transfer\x1a\x13\x63ommon/common.proto\"\x8f\x01\n\x11TransferProcessed\x12\x1f\n\x16token_amount_in_native\x18\xac\x02 \x01(\t\x12\x1c\n\x13token_amount_in_usd\x18\xad\x02 \x01(\t\x12\x1e\n\x15token_price_in_native\x18\xb6\x02 \x01(\t\x12\x1b\n\x12token_price_in_usd\x18\xb7\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.transfer_processed_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSFERPROCESSED']._serialized_start=91
  _globals['_TRANSFERPROCESSED']._serialized_end=234
# @@protoc_insertion_point(module_scope)
