# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tron/block_message.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'tron/block_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18tron/block_message.proto\x12$io.chainstream.v1.tron.tron_messages\"\xc6\x01\n\x11TransactionHeader\x12\x0c\n\x04Hash\x18\x01 \x01(\t\x12\x0b\n\x03\x46\x65\x65\x18\x02 \x01(\x03\x12\r\n\x05Index\x18\x03 \x01(\x05\x12\x12\n\nExpiration\x18\x04 \x01(\x03\x12\x0c\n\x04\x44\x61ta\x18\x05 \x01(\x0c\x12\x10\n\x08\x46\x65\x65Limit\x18\x06 \x01(\x03\x12\x11\n\tTimestamp\x18\x07 \x01(\x03\x12\x12\n\nSignatures\x18\x08 \x03(\t\x12\x11\n\x04Time\x18\t \x01(\x04H\x00\x88\x01\x01\x12\x10\n\x08\x46\x65\x65Payer\x18\n \x01(\tB\x07\n\x05_Time\"\xdc\x01\n\x0b\x42lockHeader\x12\x0e\n\x06Number\x18\x01 \x01(\x03\x12\x0c\n\x04Hash\x18\x02 \x01(\t\x12\x11\n\tTimestamp\x18\x03 \x01(\x03\x12\x12\n\nParentHash\x18\x04 \x01(\t\x12\x14\n\x0cParentNumber\x18\x05 \x01(\x03\x12\x0f\n\x07Version\x18\x06 \x01(\x05\x12\x12\n\nTxTrieRoot\x18\x07 \x01(\x0c\x12\x1d\n\x10\x41\x63\x63ountStateRoot\x18\x08 \x01(\x0cH\x00\x88\x01\x01\x12\x19\n\x11TransactionsCount\x18\t \x01(\rB\x13\n\x11_AccountStateRoot\"\x18\n\x05\x43hain\x12\x0f\n\x07\x43hainId\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tron.block_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONHEADER']._serialized_start=67
  _globals['_TRANSACTIONHEADER']._serialized_end=265
  _globals['_BLOCKHEADER']._serialized_start=268
  _globals['_BLOCKHEADER']._serialized_end=488
  _globals['_CHAIN']._serialized_start=490
  _globals['_CHAIN']._serialized_end=514
# @@protoc_insertion_point(module_scope)
