# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tron/transfers_message.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'tron/transfers_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tron import block_message_pb2 as tron_dot_block__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctron/transfers_message.proto\x12$io.chainstream.v1.tron.tron_messages\x1a\x18tron/block_message.proto\"\xc3\x01\n\tTokenInfo\x12\x15\n\rSmartContract\x18\x01 \x01(\t\x12\x11\n\tDelegated\x18\x02 \x01(\x08\x12\x13\n\x0b\x44\x65legatedTo\x18\x03 \x01(\t\x12\x14\n\x0cProtocolName\x18\x04 \x01(\t\x12\x0c\n\x04Name\x18\x05 \x01(\t\x12\x0e\n\x06Symbol\x18\x06 \x01(\t\x12\x10\n\x08\x44\x65\x63imals\x18\x07 \x01(\x05\x12\x0e\n\x06HasURI\x18\x08 \x01(\x08\x12\x10\n\x08\x46ungible\x18\t \x01(\x08\x12\x0f\n\x07\x41ssetId\x18\n \x01(\t\"\xbf\x02\n\x08Transfer\x12\x11\n\tCallIndex\x18\x02 \x01(\x04\x12\x10\n\x08LogIndex\x18\x03 \x01(\x04\x12\x0e\n\x06Sender\x18\x04 \x01(\t\x12\x10\n\x08Receiver\x18\x05 \x01(\t\x12\x0e\n\x06\x41mount\x18\x06 \x01(\t\x12\n\n\x02Id\x18\x07 \x01(\t\x12\x0b\n\x03URI\x18\x08 \x01(\t\x12\x41\n\x08\x43urrency\x18\t \x01(\x0b\x32/.io.chainstream.v1.tron.tron_messages.TokenInfo\x12\x0f\n\x07Success\x18\n \x01(\x08\x12\x0c\n\x04\x44\x61ta\x18\x0c \x01(\x0c\x12\r\n\x05Index\x18\r \x01(\r\x12R\n\x11TransactionHeader\x18\x0e \x01(\x0b\x32\x37.io.chainstream.v1.tron.tron_messages.TransactionHeader\"\xd4\x01\n\x10TransfersMessage\x12:\n\x05\x43hain\x18\x01 \x01(\x0b\x32+.io.chainstream.v1.tron.tron_messages.Chain\x12\x41\n\x06Header\x18\x02 \x01(\x0b\x32\x31.io.chainstream.v1.tron.tron_messages.BlockHeader\x12\x41\n\tTransfers\x18\x03 \x03(\x0b\x32..io.chainstream.v1.tron.tron_messages.Transferb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tron.transfers_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENINFO']._serialized_start=97
  _globals['_TOKENINFO']._serialized_end=292
  _globals['_TRANSFER']._serialized_start=295
  _globals['_TRANSFER']._serialized_end=614
  _globals['_TRANSFERSMESSAGE']._serialized_start=617
  _globals['_TRANSFERSMESSAGE']._serialized_end=829
# @@protoc_insertion_point(module_scope)
